### ISSUE TITLE
Couple of Issues - reloadOptions Function

### ISSUE THREAD

**Issue by Shando** [spaghett1c0de/DataTable-AltEditor#3]
Hi All,

Not sure if these are issues, or not, but came across the following in the reloadOptions function:

1) Should the Key & Value be the other way round in this line:

`$select.append($('<option></option>').attr('value', value).text(key);`

2) I keep getting "Object doesn't support property or method 'selectpicker'" at this line:

`$('.selectpicker').selectpicker('refresh'); // Refresh bootstrap-select`

Regards

Shando

**Comment by spaghett1c0de** [comment]
@Shando 

1. The _reloadOptions_ function takes in two kinds of data types, Array and Objects. When you provide an array of options, since it only contains one value for each option, it uses the same value for both value attribute and the text it renders. Example result:
`<option value='value'>value</option>`
When you provide objects of options, since it contains both a key and a value for each option, it uses the value as the value attribute and key for the text it renders. Example result:
`<option value='value'>key</option>`
I'm considering deprecating The Array option as the Objects option provides more context. 🤔 This Object-style implementation also eliminates the possibility of two dropdown options containing the same text that will confuse the users.

2. This is indeed a bug! Thank you for notifying me! The error is thrown when Bootstrap Select is not included in the project. I just published the fix for that issue. Make sure you get the latest version of the script.

Please lemme know if this answers and fixes your issues.

Best,
Vincent

**Comment by Shando** [comment]
@spaghett1c0de 

All good.

Regards

Shando
